# Generated by Django 3.2.23 on 2024-01-01 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('075bed7f-e564-4347-b42e-55b5aaae877e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
