# Generated by Django 3.2.23 on 2024-01-01 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0f5232f-aa78-4f90-a995-b5a2d04dc95d'), primary_key=True, serialize=False, unique=True),
        ),
    ]
