# Generated by Django 3.2.23 on 2024-01-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created_at']},
        ),
    ]
